routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminHomeController;
use App\Http\Controllers\Admin\ParametreController;
use App\Http\Controllers\Admin\PublicationController;
use App\Http\Controllers\Admin\RealisationController;
use App\Http\Controllers\Admin\ResourcePublicationController;
use App\Http\Controllers\Admin\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([
    "prefix" => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect','auth:admin']
], function () {
    Route::group(['prefix' => "admin","as"=>"admin."],function () {
        Route::prefix("home")->group(function (){
            Route::get("/", [AdminHomeController::class, "index"])->name("home");
        });
        Route::resource("services", ServiceController::class);
        Route::resource("realisations", RealisationController::class);
        //parametre
        Route::get("parametres",[ParametreController::class,"index"])->name("parametres.index");
        //publications
        Route::resource("publications",PublicationController::class);
        //resource des publication
        Route::resource("publications.resources", ResourcePublicationController::class);
    });
});

routes/web.php
<?php

use App\Http\Controllers\Client\ClientTestimonyController;
use App\Http\Controllers\Client\ServiceController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([
    "prefix" => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect']
], function () {
    Route::get("/test",function (){
       $mail = Mail::to("lucchuala@gmail.com")->send(new \App\Mail\testMail());
       dd($mail);
    });
    Route::get('/', [HomeController::class, "index"])->name("home");
    Route::get('/dashboard', [DashboardController::class, "index"])->middleware(['auth', 'verified'])->name('dashboard');
    Route::middleware('auth:web')->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    });
    //services
    Route::as("client.")->group(callback: function(){
        Route::get("services", [ServiceController::class,"index"])->name("services.index");
        Route::resource("testimonies", ClientTestimonyController::class);
    });
    Route::get("/facebook/login", [FacebookController::class, "index"])->name("facebook.login");
});

require __DIR__ . '/auth.php';

app/Models/Realisation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Realisation extends Model implements HasMedia
{
    use HasFactory,InteractsWithMedia;

    protected $guarded = [];
    protected $casts = [
        'date_realisation' => 'datetime'
    ];
}

app/Http/Controllers/Admin/RealisationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Constant\ReturnStatus;
use App\Data\Realisation\StoreRealisationData;
use App\Http\Controllers\Controller;
use App\Models\Realisation;
use Illuminate\Http\Request;
use Illuminate\Http\Testing\MimeType;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;
use Spatie\MediaLibrary\MediaCollections\Exceptions\MediaCannotBeDeleted;

class RealisationController extends Controller
{
    public function index()
    {
        $realisations = Realisation::query()->get();
        return view("admin.realisations.index",[
            "realisations"=>$realisations
        ]);
    }

    public function create()
    {
        return view("admin.realisations.create");

    }


    public function store(Request $request)
    {
        $data = StoreRealisationData::from($request);
        //je cree mon realisation
        \DB::transaction(function () use ($data,$request){
            $realisation = Realisation::query()->create([
                "titre"=>$data->titre,
                "contenu"=>$data->contenu,
                "lieu"=>$data->lieu,
                "realisateur"=>$data->realisateur,
                "date_realisation"=>$data->date_realisation,
                "nombre_jour"=>$data->nombre_jour,
                "photo"=>$request->file("photo")->store(getStoragePathFor('realisations')),
            ]);
            foreach ($data->ressources as $ressource){
                $realisation->addMedia($ressource)->toMediaCollection("ressources");
            }
        });

        //je stocke les autres images
        return redirect()->back()->with(ReturnStatus::SUCCESS,"realisation cree");
    }

    public function show(Realisation $realisation)
    {
        return view("admin.realisations.show",[
            "realisation"=>$realisation
        ]);
    }

    public function edit(Realisation $realisation)
    {
        return view("admin.realisations.edit",[
            "realisation"=>$realisation
        ]);
    }

    public function update(Request $request, Realisation $realisation)
    {
        //je valide mes donnees
        if($request->hasFile("ressources")){
            try {
                $realisation->deleteMedia("ressources");
            } catch (MediaCannotBeDeleted $e) {
                return back()->withErrors($e->getMessage());
            }
            foreach ($request->file("ressources") as $ressource){
                try {
                    $realisation->addMedia($ressource)->toMediaCollection("ressources");
                } catch (FileDoesNotExist | FileIsTooBig $e) {
                    return back()->withErrors($e->getMessage());
                }
            }
        }
        if($request->hasFile("photo")){
            \Storage::delete($realisation->photo);
            $realisation->photo = $request->file("photo")->store(getStoragePathFor("realisations"));
        }
        $realisation->contenu = $request->input("contenu");
        $realisation->lieu = $request->input("lieu");
        $realisation->nombre_jour = $request->input("nombre_jour");
        $realisation->date_realisation = $request->input("date_realisation");
        $realisation->realisateur = $request->input("realisateur");
        $realisation->titre = $request->input("titre");
        $realisation->save();
        return redirect()->back()->with(ReturnStatus::SUCCESS,"realisation mis a jour");
    }

    public function destroy(Realisation $realisation)
    {
        $realisation->delete();
        return redirect()->back()->with(ReturnStatus::SUCCESS,responseTextAfterDelete("realisations"));
    }
}

resources/views/admin/realisations/create.blade.php
@extends("layouts.dashboard.dashboard_admin_template")

@section("main-content")

    <div class="card card-primary">
        <div class="card-header">
            <h4 class="card-title">Nouvelle Realisation</h4>
        </div>
        @if($errors->any())
            <div class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </div>
        @endif
        <div class="card-body">
            <form method="post" action="{{route('admin.realisations.store')}}" class="needs-validation" novalidate enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="titre">Titre</label>
                    <input type="text" value="{{old('titre')}}" id="titre" name="titre" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "titre"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="lieu">Lieu</label>
                    <input type="text" value="{{old('lieu')}}" name="lieu" id="lieu" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "lieu"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="realisateur">Réalisateur</label>
                    <input type="text" value="{{old('realisateur')}}" name="realisateur" id="realisateur" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "realisateur"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="date_realisation">Date de réalisation</label>
                    <input type="date" name="date_realisation" value="{{old('date_realisation')}}" id="date_realisation" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "date de réalisation"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="nombre_jour">Nombre de jour</label>
                    <input type="number" name="nombre_jour" id="nombre_jour" value="{{old('nombre_jour')}}" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "nombre de jour"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="but"> Image principale</label>
                    <input name="photo" type="file" id="but" accept="image/*" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "images"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="ressources"> Autres Resources</label>
                    <input type="file" id="ressources" name="ressources[]" accept="image/*,video/*,music/*,application/pdf" class="form-control"  multiple>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "ressources"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="contenu">contenu</label>
                    <textarea name="contenu" id="contenu" class="form-control" required>{{old('contenu')}}</textarea>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "contenu"])}}
                    </div>
                </div>
                <button class="btn btn-success">Enregistrer</button>
            </form>
        </div>
    </div>
@endsection
@section("top_navigation")

@endsection

resources/views/admin/realisations/edit.blade.php
@extends("layouts.dashboard.dashboard_admin_template")

@section("main-content")

    <div class="card card-primary">
        <div class="card-header">
            <h4 class="card-title">Editer la Realisation {{$realisation->titre}}</h4>
        </div>
        @if($errors->any())
            <div class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </div>
        @endif
        <div class="card-body">
            <form method="post" action="{{route('admin.realisations.update',['realisation'=>$realisation->id])}}" class="needs-validation" novalidate enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="titre">Titre</label>
                    <input type="text" value="{{$realisation->titre}}" id="titre" name="titre" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "titre"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="lieu">Lieu</label>
                    <input type="text" value="{{$realisation->lieu}}" name="lieu" id="lieu" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "lieu"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="realisateur">Réalisateur</label>
                    <input type="text" value="{{$realisation->realisateur}}" name="realisateur" id="realisateur" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "realisateur"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="date_realisation">Date de réalisation</label>
                    <input type="date" name="date_realisation" value="{{$realisation->date_realisation}}" id="date_realisation" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "date de réalisation"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="nombre_jour">Nombre de jour</label>
                    <input type="number" name="nombre_jour" id="nombre_jour" value="{{$realisation->nombre_jour}}" class="form-control" required>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "nombre de jour"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="but"> Nouvelle Image principale <span class="text-warning">le choix est facultatif</span></label>
                    <input name="photo" type="file" id="but" accept="image/*" class="form-control">
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "images"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="ressources"> Autres Resources <span class="text-warning">le choix est facultatif</span></label>
                    <input type="file" id="ressources" name="ressources[]" accept="image/*,video/*,music/*,application/pdf" class="form-control"  multiple>

                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "ressources"])}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="contenu">contenu</label>
                    <textarea name="contenu" id="contenu" class="form-control" required>{{$realisation->contenu}}</textarea>
                    <div class="invalid-feedback">
                        {{__('validation.required', ['attribute' => "contenu"])}}
                    </div>
                </div>
                <button class="btn btn-success">Enregistrer</button>
            </form>
        </div>
    </div>
@endsection
@section("top_navigation")

@endsection

resources/views/admin/realisations/index.blade.php
@extends("templates.admin_dashboard.admin_dashboard_template")

@section("content")
    <h4 class="text-center">Listes des réaliisations.</h4>
    <div class="text-divider"></div>
    <div class="row">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Numéro</th>
                <th>Titre</th>
                <th>Lieu</th>
                <th>Date de realisation</th>
                <th>Realisateur</th>
                <th>Nombre de jour</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($realisations as $realisation)
                <tr>
                    <td>{{$loop->index+1}}</td>
                    <td>{{$realisation->titre}}</td>
                    <td>{{$realisation->lieu}}</td>
                    <td>{{$realisation->date_realisation}}</td>
                    <td>{{$realisation->realisateur}}</td>
                    <td>{{$realisation->nombre_jour}}</td>
                    <td>
                        <div class="btn-group btn-group-sm d-flex justify-content-between">
                            <a href="{{route('admin.realisations.edit',['realisation'=>$realisation->id])}}" class="btn btn-sm btn-primary">Editer</a>
                            <a href="{{route('admin.realisations.show',["realisation"=>$realisation->id])}}" class="btn btn-sm btn-info">Voir</a>
                            <form action="{{route('admin.realisations.destroy',[$realisation->id])}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm">Supprimer</button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    </div>

@endsection

@section("top_navigation")
    <nav class="navbar navbar-secondary navbar-expand-lg">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{route('admin.realisations.create')}}"  class="nav-link"><i class="fa fa-plus"></i><span>Ajouter une réalisation</span></a>
                </li>
                <li class="nav-item active">
                    <a href="#" class="nav-link"><i class="far fa-heart"></i><span>Listes des réalisations disponibles</span></a>
                </li>
            </ul>
        </div>
    </nav>
@endsection
@section("topnavigation.menuhamburger")
    @include("layouts._partials.menuhamburger")
@endsection

resources/views/admin/realisations/show.blade.php
@extends("layouts.dashboard.dashboard_admin_template")

@section("main-content")

    <div class="container">
        <div class="card card-primary">
            <div class="card-header">
                <h4 class="card-title">Détail sur la réalisation</h4>
            </div>
            <div class="card-body">
                <h3>Titre de la réalisation</h3>
                <div class="card">
                    <div class="card-header">
                        {{$realisation->titre}}
                    </div>
                    <div class="card-body">
                        <h4>Lieu</h4>
                        <div class="card-text">{{$realisation->lieu}}</div>
                        <h4>Contenu</h4>
                        <div class="card-text">{!! $realisation->contenu !!}</div>
                        <h4>Réalisateur</h4>
                        <div class="card-text">{{$realisation->realisateur}}</div>
                        <h4>Date de réalisation</h4>
                        <div class="card-text">{{$realisation->date_realisation}}</div>
                    </div>
                </div>
            </div>
            <div class="my-4">
                <h4 class="jumbotron">Images Principale</h4>
                <div class="col col-6">
                    <img src="{{asset('storage/'.$realisation->photo)}}" alt="Image du produit" class="img w-100">
                </div>
            </div>
            <div>
                <h4 class="jumbotron">Autres Resources</h4>
                <div class="row mx-4">
                    <table class="table table-bordered">
                        <thead class="thead-dark">
                        <tr>
                            <th>Type</th>
                            <th>Contenu</th>
                        </tr>
                        </thead>
                        @foreach($realisation->getMedia("ressources") as $media)
                            <tr>
                                <td>
                                    {{ ($media->type) }}
                                </td>
                                <td>
                                    <x-front.resource :src="$media->getUrl()" :type="$media->type"/>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("top_navigation")

@endsection