routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminHomeController;
use App\Http\Controllers\Admin\ParametreController;
use App\Http\Controllers\Admin\PublicationController;
use App\Http\Controllers\Admin\RealisationController;
use App\Http\Controllers\Admin\ResourcePublicationController;
use App\Http\Controllers\Admin\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([
    "prefix" => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect','auth:admin']
], function () {
    Route::group(['prefix' => "admin","as"=>"admin."],function () {
        Route::prefix("home")->group(function (){
            Route::get("/", [AdminHomeController::class, "index"])->name("home");
        });
        Route::resource("services", ServiceController::class);
        Route::resource("realisations", RealisationController::class);
        //parametre
        Route::get("parametres",[ParametreController::class,"index"])->name("parametres.index");
        //publications
        Route::resource("publications",PublicationController::class);
        //resource des publication
        Route::resource("publications.resources", ResourcePublicationController::class);
    });
});

routes/web.php
<?php

use App\Http\Controllers\Client\ClientTestimonyController;
use App\Http\Controllers\Client\ServiceController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([
    "prefix" => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect']
], function () {
    Route::get("/test",function (){
       $mail = Mail::to("lucchuala@gmail.com")->send(new \App\Mail\testMail());
       dd($mail);
    });
    Route::get('/', [HomeController::class, "index"])->name("home");
    Route::get('/dashboard', [DashboardController::class, "index"])->middleware(['auth', 'verified'])->name('dashboard');
    Route::middleware('auth:web')->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    });
    //services
    Route::as("client.")->group(callback: function(){
        Route::get("services", [ServiceController::class,"index"])->name("services.index");
        Route::resource("testimonies", ClientTestimonyController::class);
    });
    Route::get("/facebook/login", [FacebookController::class, "index"])->name("facebook.login");
});

require __DIR__ . '/auth.php';

app/Models/Publication.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Publication extends Model implements HasMedia
{
    use HasFactory,InteractsWithMedia;
    protected $casts = [
        "date_publication" => "datetime"
    ];
    protected $guarded = [];
    public function domainePublication(): BelongsTo
    {
        return $this->belongsTo(DomainePublication::class);
    }

}

app/Http/Controllers/Admin/PublicationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Constant\ReturnStatus;
use App\Data\Publication\StorePublicationData;
use App\Http\Controllers\Controller;
use App\Models\DomainePublication;
use App\Models\Publication;
use App\Services\Publication\PublicationService;
use Illuminate\Http\Request;

class PublicationController extends Controller
{
    public function index()
    {
        $publications = Publication::with("domainePublication")->get();
        $domainesPublications = DomainePublication::query()->get();
        return view("admin.publications.index")->with([
            "publications" => $publications,
            "domainesPublications"=>$domainesPublications
        ]);
    }

    public function store(StorePublicationData $storePublicationData,PublicationService $service)
    {
        $publication = $service->store($storePublicationData);
        //je renvoie vers la page d'ajout des resources
        return redirect()->route("admin.publications.resources.create",['publication'=>$publication->id]);
    }

    public function show(Publication $publication)
    {
    }

    public function edit(Publication $publication)
    {
    }

    public function update(Request $request, Publication $publication)
    {
    }

    public function destroy(Publication $publication)
    {
        $publication->delete();
        return back()->with(ReturnStatus::SUCCESS,responseTextAfterDelete('publication'));
    }
}

resources/views/admin/publications/index.blade.php
@extends("templates.admin_dashboard.admin_dashboard_template")
@section("content")
    <div class="text-divider">
        Gerer les publications
    </div>
    <hr>
    <div class="mb-3 d-flex justify-content-end">
        <button data-bs-toggle="modal" data-bs-target="#createPublicationModal" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Creer une nouvelle publication!</button>
        @include("admin.publications.includes.modalCreate")
    </div>
    <table class="table table-bordered datatable">
        <thead>
        <th>#</th>
        <th>Titre</th>
        <th>Domaine</th>
        <th>Date de publication</th>
        <th>Actions</th>
        </thead>
        <tbody>
        @foreach($publications as $publication)
            <tr>
                <td>{{$loop->index + 1}}</td>
                <td>{{$publication->titre}}</td>
                <td>{{$publication->domainePublication->libelle}}</td>
                <td>{{$publication->date_publication->isoFormat("ll")}}</td>
                <td>
                    <button class="btn btn-primary"><i class="fa fa-eye"></i></button>
                    <button class="btn btn-info"><i class="fa fa-pencil"></i></button>
                    <form class="btn btn-danger" action="{{route('admin.publications.destroy',['publication'=>$publication->id])}}" method="post"
                          onclick="if(confirm('voulez suprimez cette publication?')){submit()}">
                        @csrf
                        @method("DELETE")
                        <i class="fa fa-trash"></i>
                    </form>
                    <a href="{{route('admin.publications.resources.index',['publication'=>$publication->id])}}" class="btn btn-secondary"><i class="fa fa-image"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection